### ISSUE TITLE
Short-term Roadmap

### ISSUE THREAD

**Issue by jpochyla** [jpochyla/psst#43]
Here's what I plan on solving in the nearest future:

- [x] Feedback for invalid credentials in the Preferences dialog
- [x] Menus & shortcuts on Linux and Windows
- [x] Media key support on Mac
- [ ] Infinite scrolling or pagination for long playlists and libraries
